version: "3.9"

services:

  # ─────────────────────────────────────────────────
  # SERVICE 1: PostgreSQL Database
  # ─────────────────────────────────────────────────
  db:
    image: postgres:16-alpine
    container_name: reactdash_db
    restart: always
    environment:
      POSTGRES_DB: database_dash
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─────────────────────────────────────────────────
  # SERVICE 2: Fastify Backend Server
  # ─────────────────────────────────────────────────
  backend:
    #forget to add build thats why instead of building new code it was pointing to old pre-built version of github
    build: ./server
    image: ghcr.io/apoorvs549-lang/legal-dash-backend:latest
    container_name: reactdash_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_NAME: database_dash
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      PORT: 3000
      HOST: 0.0.0.0
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://13.63.65.240
    volumes:
      - ./server/uploads:/usr/src/app/uploads

    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /reactdashboard/backend
        awslogs-stream: backend-server
        awslogs-create-group: "true"
    depends_on:
      db:
        condition: service_healthy

  # ─────────────────────────────────────────────────
  # SERVICE 3: React Frontend (Nginx)
  # ─────────────────────────────────────────────────
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: http://13.63.65.240:3000
    image: reactdash_frontend_local:latest
    container_name: reactdash_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

# ─────────────────────────────────────────────────
# VOLUMES: Persistent storage for the database
# ─────────────────────────────────────────────────
volumes:
  pgdata:
